### ISSUE TITLE
Main branch is behind in commits

### ISSUE THREAD

**Issue by 05-Arnav-Gupta** [05-Arnav-Gupta/Climate-Change-TIMES_NIE_BINARY_HACKS#1]
The main branch is lagging behind 4 commits than index branch. GIthub pages also setup with index instead of main.

**Comment by LockDown-Ammo** [comment]
Exam on monday bro....

**Comment by 05-Arnav-Gupta** [comment]
I remember you could have told me on whatsapp you know...

**Comment by LockDown-Ammo** [comment]
Why does this cringy repo still exist.... like dude what is this.....

**Comment by 05-Arnav-Gupta** [comment]
> Why does this cringy repo still exist.... like dude what is this.....

I have no idea its just there
